Add SDSS-V pixBias and pixFlat files

diff --git a/bin/specflat_version b/bin/specflat_version
--- a/bin/specflat_version
+++ b/bin/specflat_version
@@ -1,25 +1,11 @@
 #!/bin/sh
 #------------------------------------------------------------------------------
-# Script to return SVN version of the specflat product.
-# Change "template_version" to the name of your product to get it to work.
-# You will find it after 'CHANGE THIS LINE'.
-# Don't forget to run:
-#   svn propset svn:keywords HeadURL template_version
-#   svn ci -m "setting keywords property to HeadURL" template_version
-# once you have added this to your new SVN product
+# Script to return GIT version of the specflat product.
 #
-# For trunk and exported the script uses the $TEMPLATE_DIR/bin directory to
-# compute the svnversion.  This is because calculating the full svnversion
-# on a product like speclog can take a long time.
 #
 # Written by C. Loomis, Princeton;
 # Modified by Michael Blanton, Gary Kushner and Ben Weaver
-#
-# Note /bin/sh is preferred over /bin/bash because many bash users do EUPS
-# setups in their ~/.bashrc file.  If they have $BASH_ENV set as well, then
-# the ~/.bashrc file will be read before executing this script.  This may
-# result in a different product version being setup prior to the execution
-# of this script.  Another good reason to use tcsh.
+# Modified by Sean Morrison for GIT
 #------------------------------------------------------------------------------
 #
 # This will inhibit glob processing, just in case regexes have lots of * in
@@ -39,31 +25,35 @@ eval "myDir=\$${myEnv}"
 # The following line will include an URL name after the colon
 # for any SVN version.
 #
-svnURL='$HeadURL: https://svn.sdss.org/data/sdss/specflat/tags/v1_33/bin/specflat_version $'
+#svnURL='$HeadURL: https://svn.sdss.org/data/sdss/specflat/tags/v1_33/bin/specflat_version $'
 #
 # Special case the trunk, which we want to recognize as a version named "trunk"
 #
-svnTag=$(echo "${svnURL}" | sed 's,^$HeadURL: .*/trunk/,trunk/,; s, \$$,,' | sed "s,/${myName},,")
-svnVersion=$(svnversion "${myDir}/bin")
-if test "${svnTag}" = "trunk"; then
-    echo "trunk ${svnVersion}"
-    exit 0
-fi
+#svnTag=$(echo "${svnURL}" | sed 's,^$HeadURL: .*/trunk/,trunk/,; s, \$$,,' | sed "s,/${myName},,")
+#svnVersion=$(svnversion "${myDir}/bin")
+#if test "${svnTag}" = "trunk"; then
+#    echo "trunk ${svnVersion}"
+#    exit 0
+#fi
+gitVersion=$(git --git-dir=${myDir}/.git tag)
+gitVersion=( $gitVersion )
+gitVersion=${gitVersion[-1]}
 #
 # Look for the tag name
 #
 # To change output to "tag $tag" and "branch $branch" change "\3" to "\1 \3"
-svnTag=$(perl -pe 's{^\$HeadURL: .*/(tag|branch)(s|es)/(.*)/'"${myName}"' \$$}{\3}' <<< "${svnURL}")
-if test -z "${svnTag}" || $(echo "${svnTag}" | grep -s -q '/') ; then
-    # Noisy failure:
-    echo "NOTAG: unparseable ${svnVersion} ${svnURL}"
-    # Quiet failure:
-    # echo "NOTAG: unparseable"
-    exit 1
-fi
+#svnTag=$(perl -pe 's{^\$HeadURL: .*/(tag|branch)(s|es)/(.*)/'"${myName}"' \$$}{\3}' <<< "${svnURL}")
+#if test -z "${svnTag}" || $(echo "${svnTag}" | grep -s -q '/') ; then
+#    # Noisy failure:
+#    echo "NOTAG: unparseable ${svnVersion} ${svnURL}"
+#    # Quiet failure:
+#    # echo "NOTAG: unparseable"
+#    exit 1
+#fi
 #
 # Print the tag & exit nicely.
 #
-echo ${svnTag}
+echo ${gitVersion}
+#echo ${svnTag}
 exit 0
 
